language: php
notifications:
  email:
  - guenther.cwioro@bitmovin.net
  - bitcodin-php@bitmovin.net
  - dominic.miglar@bitmovin.net

before_install:
- openssl aes-256-cbc -K $encrypted_2dbf7e7227fa_key -iv $encrypted_2dbf7e7227fa_iv -in test/config.json.enc -out test/config.json -d

install:
- composer update
- composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs

script:
  - phpunit

after_success:
  - travis_wait 30 php vendor/bin/coveralls -v
